name: mdt
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - pip
  - networkx
  - pyyaml
  - prefect>=2.0.0
  - prefect-dask
  - dask
  - dask-jobqueue
  - xarray
  - pandas
  - numpy
  - scipy
  - esmpy  # Required by monet/xregrid for regridding and pairing
  - pip:
    - -e .
